---
title: "Introduction to Multivariate Data Visualization"
output: html_document
runtime: shiny_prerendered
author: Fabian Beck and Shahid Latif
description: "An introduction to data visualization that focuses on the explorative analysis of multivariate (tabular) data and uses interactive examples in R."
---

**You are viewing the archivable, non-interactive version of the document. To run the main interactive version, please visit: https://github.com/vis-uni-bamberg/mv-vis**

This version is citable via [DOI: 10.5281/zenodo.6523081](https://doi.org/10.5281/zenodo.6523081).

```{r setup, include=FALSE}
library(learnr)
library(ggplot2)
library(GGally)

world <- read.csv("https://raw.githubusercontent.com/vis-uni-bamberg/mv-vis/main/data/world_dataset.csv", header=TRUE)

```

```{r child = 'sections/section_1.Rmd'}
```

```{r child = 'sections/section_2.Rmd'}
```

```{r child = 'sections/section_3.Rmd'}
```

```{r child = 'sections/section_4.Rmd'}
```

```{r child = 'sections/about.Rmd'}
```