## Exercise

This exercise provides the opportunity to practice what you have learned about data visualization with a realistic example. It involves selecting a dataset and performing an exploratory visual analysis. 

### Tools

You can visualize the data with R as introduced in this tutorial, or use Tableau, Excel, or any other visualization tool for your analysis. The difference between the tools are the following, and there are good resources to quickly familiarize with them if you are not yet comfortable enough to start your visual data analysis.

* **[R](https://www.r-project.org/)**, as a you have seen, allows creating advanced visualizations with a few lines of code. Although the exercise can be mostly performed with the commands you know from the previous examples, a few extra commands and options to filter the data or to enrich the visualizations with legends and labels could be necessary. For a quick reference, we refer to this [R tutorial](https://www.w3schools.com/r/default.asp) and this [*ggplot2* cheat sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/master/data-visualization.pdf). 

* **[Tableau Public](https://public.tableau.com/s/)** is a very powerful tool to create and publish visualizations. It has an intuitive graphical user interface and does not require any coding. Tableau Public offers a series of [video tutorials](https://public.tableau.com/en-us/s/resources). These video tutorials are hands-on; you can easily follow along by downloading the associated datasets that are provided with them.

* **Microsoft Excel**, a spreadsheet tool that everybody has probably used before, also has basic support for creating visualizations. You can find a very [concise guide](https://guides.library.duke.edu/excel/visualization) from *Duke University* to understand the process of creating most of the well-known charts. For more advance visualizations in Excel, you can watch the 50 minute hands-on [video tutorial](https://www.youtube.com/watch?v=K74_FNnlIF8). 

### Data Selection

As a starting point of this exercise, you pick one dataset from the **two datasets** listed below. Having selected the dataset---**but prior to analysis**---you should note down **an overarching question** you would like to investigate. Then, come up with **two to three specific questions** (by taking a closer look at the dataset) that would help you in answering the overarching question. To facilitate the process, we have listed down both overarching and specific questions for each scenario. Please feel free to use them as your questions or come up with different ones if you like. 

In the following, we provide two different scenarios and datasets for you to choose from. You **may only work with one scenario and dataset**.

<!-- todo: add sources and links to descriptions of the vars -->

#### Scenario 1 -- Motion Pictures Data

This dataset consists of 3,201 movies data gathered in 2010. The data includes 16 different attributes of movies including titles, genres, box office revenues, *IMDB* rankings, and *Rotten Tomatoes* ratings.

**Sample Analysis Questions**

Overarching Question: What factors influence the box office revenue of motion pictures?

Specific Questions:

1. How do film makers set the release dates for various kinds of films?

2. How do ratings of moviegoers and fans relate to the box office success of films?

3. Do you observe any impact of production budget of different kinds of films on their financial success?

#### Scenario 2 -- Bike Buyers Data

This data consists of 1000 different people who thought about buying a bicycle at one stage of their lives but ended up either buying or not buying one. The data consists of 13 different attributes of these people including their income, marital status, number of children, age, gender, commute distance to workplace, and their final decision of buying the bicycle.

**Sample Analysis Questions**

Overarching Question: What social characteristics of people relate to the likelihood to buy a bicycle?

Specific Questions:

1. How does the family status (e.g., single or married with/without kids, etc.) relate to the decision of buying a bicycle?

2. Are people from Europe with short commute distances and having a desk job---as one might speculate---indeed more likely to buy a bicycle?

3. How do the age, income, and gender of a person correlate with the decision?

### Exploratory Visual Analysis

You should begin your analysis by looking into the shape and structure of your dataset. For instance: What variables does the dataset contain? How are the data values distributed? Do variables include missing values or outliers that may influence the analysis? Are there any surprising relationships among the variables?

Next, you start investigate **the specific questions**, as well as new questions that may arise during the exploration process. The goal is to come up with non-obvious and non-trivial insights. In response to each specific question, start by creating a visualization that might provide a useful answer. Then, refine the visualization (by adding additional variables, changing axis scales, filtering or sub-setting data, etc.) to develop better perspectives and explore unexpected observations. 

### Deliverable

Submit your analysis findings as a PDF report consisting of **5 captioned visualizations**. Each visualization should be a screenshot exported from the data visualization system, **accompanied with the specific analysis question as title and a caption (1--4 sentences long) describing the non-trivial insight(s) learned from that visual**. Provide sufficient detail for each caption such that anyone could read through your report and understand what you have learned. For additional clarity, you are free, but not required, to annotate your visualizations to draw attention to specific features of the data (you may perform highlighting within the visualization tool itself, or draw annotations on the exported image).

### R Playground

If you intend to use **R** for your analysis, you can use the following window to begin your analysis. The required libraries and datasets have already been loaded.

```{r playground, exercise=TRUE}
#Access the Scenario 1 dataset as `movies`
#Access the Scenario 2 dataset as `bikes`

# See the structure of the dataset
head(movies)

```
